version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_sistema_gastos
    restart: always
    environment:
      MYSQL_DATABASE: sistema_gastos_clientes_db
      MYSQL_ROOT_PASSWORD: tu_clave
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
